# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c2b18b136eab1cd68e0eca3d7ef5c224e4e547dcd5c8db51d7521e192c7b34859604cb5bfd2a795409259c52447d36225c6793caccc9add5f6841e570ba1965

test:
  secret_key_base: 9a9891c59ebd1d78e1a6a7e8a26ee0f2d2595096427b4a7f0e864df292a8994e9ddaff1ec5894560fc912cf6620b3431823fbfad301bf6e3bd49e0cda7d9e292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
